# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/constant_resolver/all/constant_resolver.rbi
#
# constant_resolver-0.1.5

class ConstantResolver
  def config; end
  def file_map; end
  def initialize(root_path:, load_paths:, inflector: nil); end
  def resolve(const_name, current_namespace_path: nil); end
  def resolve_constant(const_name, current_namespace_path, original_name: nil); end
  def resolve_traversing_namespace_path(const_name, current_namespace_path); end
end
class ConstantResolver::Error < StandardError
end
class Anonymous_Struct_2 < Struct
  def location; end
  def location=(_); end
  def name; end
  def name=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class ConstantResolver::ConstantContext < Anonymous_Struct_2
end
class ConstantResolver::DefaultInflector
  def camelize(string); end
end
