# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `guard-compat` gem.
# Please instead update this file by running `bin/tapioca gem guard-compat`.

module Guard; end

module Guard::Compat
  class << self
    def matching_files(plugin, files); end
    def watched_directories; end
  end
end

module Guard::Compat::UI
  class << self
    def color(text, *colors); end
    def color_enabled?; end
    def debug(message, options = T.unsafe(nil)); end
    def deprecation(message, options = T.unsafe(nil)); end
    def error(message, options = T.unsafe(nil)); end
    def info(message, options = T.unsafe(nil)); end
    def notify(msg, options = T.unsafe(nil)); end
    def warning(message, options = T.unsafe(nil)); end
  end
end

class Guard::Plugin
  def initialize(_options = T.unsafe(nil)); end
end
