# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/parser/all/parser.rbi
#
# parser-2.7.2.0

module Parser
end
module Parser::Source
end
class Parser::Source::Map
  def ==(other); end
  def column; end
  def expression; end
  def first_line; end
  def initialize(expression); end
  def initialize_copy(other); end
  def last_column; end
  def last_line; end
  def line; end
  def node; end
  def node=(node); end
  def to_hash; end
  def update_expression(expression_l); end
  def with(&block); end
  def with_expression(expression_l); end
end
module Parser::AST
end
class Parser::AST::Node < AST::Node
  def assign_properties(properties); end
  def loc; end
  def location; end
end
